# -*- coding: utf-8 -*-
"""bookwordscount.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UiL686VoKgwAF924J4Jfwk5U-v-fs-3O

Importing required libraries
"""

from pyspark.sql import SparkSession
from pyspark.sql import functions as f

"""Creating  a spark session"""

spark=SpaekSession.builder.appName("Wordcount").getOrCreate()

"""Reading each line in book into a dataframe"""

df=spark.read.text("book.txt")

"""spliting using a regular expression that extracts words"""

words=df.select(f.explode(f.split(df.value,"\\W+")).alias("word"))
words.filter(words.word!="")

"""changing every word to lowercase"""

lowercasewords=words.select(f.lower(words.word)).alias("word")

"""counting the each occurences of word"""

wordcounts=lowercasewords.groupBy("word").count()

"""sorting by count"""

sorted=wordcounts.sort("count")

"""displaying the results"""

sorted.show(sorted.count())