# -*- coding: utf-8 -*-
"""fakefriends_avg_friends_pyspark.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qa8uPQhVGY7V3Km_wuK9DTnaFhqVwYH-

importing required libraries
"""

from pyspark.sql import SparkSession
from pyspark.sql import functions as f

"""Creating a sparksession"""

spark=SparkSession.builder.appName("friendsbyage").getOrCreate()

"""reading dataset"""

lines=spark.read.option("header","true").option("inferSchema","true").csv("fakefriends-header.csv")

"""selecting only age and numfiends columns"""

friendsbyage=lines.select("age","friends")

"""grouping by age and computing avg and sorting according to age"""

friendsbyage.groupBy("age").avg("friends").sort("age").show()

"""instead of having 6 precision floating point rounding it to 2 decimal places"""

friendsbyage.groupBy("age").agg(f.round(f.avg("fiends"),2)).sort("age").show()

"""changing column name by giving alias name"""

friendsbyage.groupBy("age").agg(f.round(f.avg("friends"),2).alias("friends_avg")).sort("äge").show()

spark.stop()