# -*- coding: utf-8 -*-
"""fakefriends_dataframe_operations_pyspark.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sd2MQAOjvdGvmneRAbFRdnUNoTcfmW_0

Importing Libraries
"""

from pyspark import SparkSession

"""Creating sparkseesion"""

spark=SparkSession.builder.appNmae("SparkSQL").getOrCreate()

"""we used getorcreate cause only one spark session is possible to run on cluster or local

reading csv file having header and allowing spark to infer schema
"""

people=spark.read.option("header","true").option("inferSchema","true").csv("fakefriends-header.csv")

"""printing inferred schema"""

people.printSchema()

"""displaying required column"""

people.select("name").show()

"""filtering teenagers"""

people.filter(people.age<21).show()

"""grouping by age"""

people.groupBy("age").count().show()

"""make everyone 10 years older"""

people.select(people.name,people.age+10).show()

"""stopping spark session"""

spark.stop()